
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))


print("Results of Arithmetic Operations:")
print("Addition (+)       =", a + b)
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
print("Subtraction (-)    =", a - b)
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
print("Multiplication (*) =", a * b)
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
print("Division (/)       =", a / b)
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
print("Modulus (%)        =", a % b)
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
print("Exponentiation (**) =", a ** b)
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
print("Floor Division (//) =", a // b)
